"""add game table \ add rating in user

Revision ID: a156cae51fb4
Revises: 6753884ddaab
Create Date: 2024-11-11 17:38:56.616148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a156cae51fb4'
down_revision: Union[str, None] = '6753884ddaab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_1_id', sa.Integer(), nullable=False),
    sa.Column('player_2_id', sa.Integer(), nullable=True),
    sa.Column('turnsX', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('turnsO', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['player_2_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rating')
    op.drop_table('game')
    # ### end Alembic commands ###
